// import './js/header-modal-online';
// import './js/header-modal-offline';
// import './js/switcher';
import './js/cards';
// import './js/ball-in-field';
// import './js/calculate-hour-or-minutes';
// import './js/game-stone-scissors--paper';
// import './js/leap-year-or-no';
// import './js/dino';
import './js/memory-game';
