import './js/header-modal-online';
import './js/header-modal-offline';
import './js/switcher';
import './js/cards';
import './js/games/ball-in-field';
import './js/games/calculate-hour-or-minutes';
import './js/games/leap-year-or-no';
import './js/games/guess-the-number';
import './js/games/memory-game';
// import './js/dino';
import './js/games/game-stone-scissors--paper';
// import './js/leap-year-or-no';
// import './js/dino';
// import './js/leap-year-or-no';
import './js/switcher';
